### ISSUE TITLE
Schema?

### ISSUE THREAD

**Issue by manishmalik** [MuShMe/MuShMe#1]
We should prepare the schema for our db. @rootAvish and @AntrikshA  if you already have one then post it here else I will have to prepare one by tomorrow.

**Comment by rootAvish** [comment]
Please do so by all means, I don't have anything right now.

**Comment by manishmalik** [comment]
Okay, this is how our DB Schema will look like. It's open for discussion if you have any suggestion or any improvement for this schema then please try to come up with your  schema or comment it. We should prepare the Schema and ER diagram by the end of this week. So come up with your ideas and innovation.
![schema](https://cloud.githubusercontent.com/assets/3881393/3865845/18d4c5da-1fae-11e4-9d2d-239865ff6a05.jpg)

**Comment by manishmalik** [comment]
@rootAvish , http://creately.com/ use this website. Make sure you register before working on their website else you will lose the schema as I did.
